// pasteboardwatch — says when the clipboard changes, and what kinds it holds.
//
// macOS has no clipboard notification, but NSPasteboard keeps a changeCount
// that moves on every write. Watching that number four times a second costs
// nothing; reading the contents costs, especially for images. So this helper
// watches the number and the app reads only when it has moved.
//
// Protocol on stdout, one JSON object per line:
//   first line   {"ok":true,"change":41}
//   then         {"change":42,"types":["public.utf8-plain-text",…],"concealed":false}
// Types are the pasteboard's own UTIs. `concealed` is true when a password
// manager or autofill has marked the paste as not to be remembered. Exits 0
// when stdin closes. Contents are never read here.
//
//   swiftc -O -o pasteboardwatch pasteboardwatch.swift

import AppKit
import Foundation

let secretTypes: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword", "com.typeit4me.clipping"]

func emit(_ object: [String: Any]) {
    guard let data = try? JSONSerialization.data(withJSONObject: object), let line = String(data: data, encoding: .utf8) else { return }
    print(line)
    fflush(stdout)
}

let board = NSPasteboard.general
var last = board.changeCount
emit(["ok": true, "change": last])

Thread.detachNewThread {
    _ = FileHandle.standardInput.readDataToEndOfFile()
    exit(0)
}

let timer = Timer(timeInterval: 0.25, repeats: true) { _ in
    let count = board.changeCount
    guard count != last else { return }
    last = count
    let types = (board.types ?? []).map { $0.rawValue }
    emit(["change": count, "types": types, "concealed": types.contains { secretTypes.contains($0) }])
}
RunLoop.main.add(timer, forMode: .common)
RunLoop.main.run()
