/**
 * Clipboard history: what you copied, kept on this Mac, only if you ask.
 *
 * macOS has no clipboard notification, but NSPasteboard's changeCount moves on
 * every write. A small helper (pasteboardwatch) watches that number and says
 * when it moved and which types the pasteboard holds; the store reads only
 * then. Without the helper it falls back to looking at the types every half
 * second and reading when they changed. Password managers and autofill mark
 * their pastes as concealed or transient; those are never read. Copying an
 * item back writes it to the pasteboard and the store ignores that one write.
 * Nothing leaves the Mac: the history is a JSON file under ~/.notchlight with
 * owner-only permissions.
 *
 * Text and images. An image is kept as a PNG data URL with a small thumbnail
 * beside it, compared by a hash of its bytes, and never re-read while the
 * pasteboard has not changed. Limits are hard: a history size, a per-item
 * size, a total byte budget and a pinned budget, so pinning cannot grow the
 * file without bound.
 */
import { EventEmitter } from 'node:events';
import { createHash, randomUUID } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { type ClipboardItem, type ClipboardSnapshot, EMPTY_CLIPBOARD } from '../shared/companion';
import { logEvent } from './lifecycle';

/** An image off the pasteboard: the PNG bytes, its size, and a small preview the renderer can show cheaply. */
export interface PasteboardImage { png: Buffer; width: number; height: number; thumb: string }

/** The subset of a clipboard the store needs, asynchronous like Electron's, so tests can hand in a fake. */
export interface Pasteboard {
  /** Every type on the pasteboard: 'text/plain', 'image/png', and the raw macOS markers in SKIPPED_FORMATS when present. */
  availableFormats(): Promise<string[]>;
  readText(): Promise<string>;
  writeText(text: string): Promise<void>;
  readImage(): Promise<PasteboardImage | null>;
  writeImage(png: Buffer): Promise<void>;
}

/** Pasteboard types that say "do not remember this". */
export const SKIPPED_FORMATS = ['org.nspasteboard.ConcealedType', 'org.nspasteboard.TransientType', 'org.nspasteboard.AutoGeneratedType', 'com.agilebits.onepassword', 'com.typeit4me.clipping'];
export const MAX_TEXT_BYTES = 20 * 1024;
export const MAX_IMAGE_BYTES = 2 * 1024 * 1024;
export const MAX_TOTAL_BYTES = 8 * 1024 * 1024;
export const MAX_PINNED = 20;
export const POLL_MS = 500;
const DATA_PREFIX = 'data:image/png;base64,';

const hashOf = (data: string | Buffer) => createHash('sha1').update(data).digest('hex');
const firstLine = (text: string) => {
  const line = text.replace(/\s+/g, ' ').trim();
  return line.length > 140 ? line.slice(0, 139) + '…' : line;
};

export function toItem(text: string, now = Date.now()): ClipboardItem {
  const bytes = Buffer.byteLength(text, 'utf8');
  const trimmed = text.trim();
  let kind: ClipboardItem['kind'] = 'text';
  try { const u = new URL(trimmed); if ((u.protocol === 'http:' || u.protocol === 'https:') && !/\s/.test(trimmed)) kind = 'url'; } catch { /* not a URL */ }
  return { id: randomUUID(), kind, text, preview: firstLine(text), host: kind === 'url' ? new URL(trimmed).hostname : undefined, lines: text.split('\n').length, bytes, at: now, pinned: false };
}

export function toImageItem(image: PasteboardImage, now = Date.now()): ClipboardItem {
  return { id: randomUUID(), kind: 'image', text: '', preview: `${image.width}×${image.height} image`, lines: 1, bytes: image.png.length, at: now, pinned: false, data: DATA_PREFIX + image.png.toString('base64'), thumb: image.thumb, width: image.width, height: image.height };
}

const pngOf = (item: ClipboardItem) => Buffer.from((item.data ?? '').slice(DATA_PREFIX.length), 'base64');

type Read = { hash: string; text?: string; image?: PasteboardImage };

export class ClipboardStore extends EventEmitter {
  private items: ClipboardItem[] = [];
  private timer: NodeJS.Timeout | null = null;
  private lastHash: string | null = null;
  private ignoreHash: string | null = null;
  private paused = false;
  private enabled = false;
  private watched = false;
  private limit = 50;
  private queue: Promise<unknown> = Promise.resolve();
  private loaded = false;
  private polling = false;
  private again = false;
  constructor(private file: string, private pasteboard: Pasteboard, private pollMs = POLL_MS) { super(); }

  current(): ClipboardSnapshot {
    return { ...EMPTY_CLIPBOARD, enabled: this.enabled, paused: this.paused, items: this.items, limit: this.limit };
  }
  private emitState() { this.emit('change', this.current()); }
  private serial<T>(run: () => Promise<T>): Promise<T> {
    const next = this.queue.then(run, run);
    this.queue = next.catch(() => {});
    return next;
  }

  async load(): Promise<void> {
    try {
      const raw = JSON.parse(await fs.readFile(this.file, 'utf8'));
      if (Array.isArray(raw.items)) {
        this.items = raw.items.flatMap((v: unknown): ClipboardItem[] => {
          const i = v as ClipboardItem;
          if (!i || typeof i !== 'object' || typeof i.id !== 'string') return [];
          if (i.kind === 'image') {
            if (typeof i.data !== 'string' || !i.data.startsWith(DATA_PREFIX) || typeof i.thumb !== 'string') return [];
            const bytes = pngOf(i).length;
            if (!bytes || bytes > MAX_IMAGE_BYTES) return [];
            return [{ ...i, text: '', lines: 1, bytes, preview: `${i.width ?? '?'}×${i.height ?? '?'} image`, pinned: !!i.pinned }];
          }
          if (typeof i.text !== 'string' || (i.kind !== 'text' && i.kind !== 'url')) return [];
          return [{ ...toItem(i.text, i.at), id: i.id, pinned: !!i.pinned }];
        }).slice(0, 200);
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') logEvent('notchlight', 'clipboard history could not be read; starting empty');
    }
    this.loaded = true;
    this.enforce();
    this.emitState();
  }

  private async persist(): Promise<void> {
    await fs.mkdir(path.dirname(this.file), { recursive: true });
    const temporary = `${this.file}.${randomUUID()}.tmp`;
    try {
      await fs.writeFile(temporary, JSON.stringify({ items: this.items }) + '\n', { mode: 0o600 });
      await fs.rename(temporary, this.file);
    } finally { await fs.rm(temporary, { force: true }).catch(() => {}); }
  }

  /** Turn capture on or off; off stops watching and forgets nothing. */
  configure(enabled: boolean, limit: number): void {
    const size = [20, 50, 100].includes(limit) ? limit : 50;
    const changed = enabled !== this.enabled || size !== this.limit;
    const wasEnabled = this.enabled;
    this.enabled = enabled; this.limit = size;
    if (enabled && !wasEnabled) {
      // What is there now was copied before we were asked to watch; polling starts after that is noted.
      void this.safeRead().then(read => { this.lastHash = read?.hash ?? null; this.syncTimer(); });
      logEvent('notchlight', 'clipboard capture on');
    } else if (!enabled && wasEnabled) {
      this.syncTimer();
      logEvent('notchlight', 'clipboard capture off');
    }
    if (this.enforce() || changed) { void this.serial(() => this.persist()).catch(() => {}); this.emitState(); }
  }

  /**
   * A change-count helper is (or is no longer) telling us when the pasteboard
   * moves. While it is, the interval stays off and the helper's word is enough.
   */
  setWatched(watched: boolean): void {
    this.watched = watched;
    this.syncTimer();
  }

  /** The helper saw the pasteboard move. Concealed pastes are noted as seen and never read. */
  notifyChange(change: { types: string[]; concealed: boolean }): void {
    if (!this.enabled || this.paused || !this.loaded) return;
    if (change.concealed) { this.lastHash = null; return; }
    void this.poll();
  }

  private syncTimer() {
    const wantInterval = this.enabled && !this.watched;
    if (wantInterval && !this.timer) this.timer = setInterval(() => void this.poll(), this.pollMs);
    if (!wantInterval && this.timer) { clearInterval(this.timer); this.timer = null; }
  }

  setPaused(paused: boolean): void {
    if (typeof paused !== 'boolean' || paused === this.paused) return;
    this.paused = paused;
    if (!paused) void this.safeRead().then(read => { this.lastHash = read?.hash ?? null; });
    logEvent('notchlight', `clipboard capture ${paused ? 'paused' : 'resumed'}`);
    this.emitState();
  }

  stop(): void { if (this.timer) clearInterval(this.timer); this.timer = null; }

  /**
   * Read the pasteboard if it is safe to; null when concealed, transient, empty
   * or too large. An image wins over text when both are there — a copied
   * picture from a browser also carries its markup.
   */
  private async safeRead(): Promise<Read | null> {
    try {
      const formats = await this.pasteboard.availableFormats();
      if (formats.some(f => SKIPPED_FORMATS.includes(f))) return null;
      if (formats.includes('image/png')) {
        const image = await this.pasteboard.readImage();
        if (!image || !image.png.length || image.png.length > MAX_IMAGE_BYTES) return null;
        return { hash: hashOf(image.png), image };
      }
      const text = await this.pasteboard.readText();
      if (!text || !text.trim()) return null;
      if (Buffer.byteLength(text, 'utf8') > MAX_TEXT_BYTES) return null;
      return { text, hash: hashOf(text) };
    } catch { return null; }
  }

  /** One look at the pasteboard. Public so tests can drive it without waiting. */
  async poll(): Promise<void> {
    if (!this.enabled || this.paused || !this.loaded) return;
    if (this.polling) { this.again = true; return; }
    this.polling = true;
    try {
      const read = await this.safeRead();
      if (!read || !this.enabled || this.paused) return;
      if (read.hash === this.lastHash) return;
      this.lastHash = read.hash;
      if (read.hash === this.ignoreHash) { this.ignoreHash = null; return; }
      if (read.image) this.remember(toImageItem(read.image), read.hash);
      else if (read.text !== undefined) this.remember(toItem(read.text), read.hash);
    } finally {
      this.polling = false;
      if (this.again) { this.again = false; void this.poll(); }
    }
  }

  private remember(item: ClipboardItem, hash: string): void {
    const existing = this.items.find(i => i.kind === item.kind && (item.kind === 'image' ? i.bytes === item.bytes && hashOf(pngOf(i)) === hash : i.text === item.text));
    this.items = existing ? [{ ...existing, at: Date.now() }, ...this.items.filter(i => i !== existing)] : [item, ...this.items];
    this.enforce();
    void this.serial(() => this.persist()).catch(() => {});
    this.emitState();
  }

  /** Apply the caps. Pinned items survive the history size but not the byte or pin budgets. Returns whether anything was dropped. */
  private enforce(): boolean {
    const before = this.items.length;
    let pins = 0;
    const kept: ClipboardItem[] = [];
    let unpinned = 0, bytes = 0;
    for (const item of this.items) {
      if (item.pinned) { if (pins >= MAX_PINNED) continue; pins++; }
      else { if (unpinned >= this.limit) continue; unpinned++; }
      if (bytes + item.bytes > MAX_TOTAL_BYTES) continue;
      bytes += item.bytes;
      kept.push(item);
    }
    this.items = kept;
    return kept.length !== before;
  }

  private find(id: unknown): ClipboardItem {
    const item = typeof id === 'string' && this.items.find(i => i.id === id);
    if (!item) throw new Error('That item is no longer in the history.');
    return item;
  }

  /** Put an item back on the pasteboard. The store ignores this one write. */
  copy(id: unknown): Promise<void> {
    return this.serial(async () => {
      const item = this.find(id);
      if (item.kind === 'image') {
        const png = pngOf(item);
        this.ignoreHash = hashOf(png);
        await this.pasteboard.writeImage(png);
      } else {
        this.ignoreHash = hashOf(item.text);
        await this.pasteboard.writeText(item.text);
      }
      this.lastHash = this.ignoreHash;
      this.items = [{ ...item, at: Date.now() }, ...this.items.filter(i => i !== item)];
      await this.persist();
      this.emitState();
    });
  }

  pin(id: unknown, pinned: unknown): Promise<void> {
    if (typeof pinned !== 'boolean') return Promise.reject(new Error('Invalid pin.'));
    return this.serial(async () => {
      const item = this.find(id);
      if (pinned && !item.pinned && this.items.filter(i => i.pinned).length >= MAX_PINNED) throw new Error(`Up to ${MAX_PINNED} items can be pinned. Unpin one first.`);
      this.items = this.items.map(i => i === item ? { ...i, pinned } : i);
      this.enforce();
      await this.persist();
      this.emitState();
    });
  }

  remove(id: unknown): Promise<void> {
    return this.serial(async () => {
      const item = this.find(id);
      this.items = this.items.filter(i => i !== item);
      await this.persist();
      this.emitState();
    });
  }

  /** Forget the history. Pins stay unless asked for explicitly. */
  clear(includePinned: unknown): Promise<void> {
    if (typeof includePinned !== 'boolean') return Promise.reject(new Error('Invalid clear.'));
    return this.serial(async () => {
      this.items = includePinned ? [] : this.items.filter(i => i.pinned);
      await this.persist();
      logEvent('notchlight', `clipboard history cleared${includePinned ? ' including pins' : ''}`);
      this.emitState();
    });
  }
}
