/**
 * Clipboard history: what you copied, kept on this Mac, only if you ask.
 *
 * macOS has no clipboard change event, so while enabled the store polls the
 * pasteboard every half second and compares a hash of the text against the
 * last one seen. Password managers and autofill mark their pastes as concealed
 * or transient; those are never read. Copying an item back writes it to the
 * pasteboard and the poller ignores that one write. Nothing leaves the Mac:
 * the history is a JSON file under ~/.notchlight with owner-only permissions.
 *
 * Limits are hard: a history size, a per-item size, a total byte budget, and
 * a pinned budget, so pinning cannot grow the file without bound.
 */
import { EventEmitter } from 'node:events';
import { createHash, randomUUID } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { type ClipboardItem, type ClipboardSnapshot, EMPTY_CLIPBOARD } from '../shared/companion';
import { logEvent } from './lifecycle';

/** The subset of a clipboard the store needs, asynchronous like Electron's, so tests can hand in a fake. */
export interface Pasteboard {
  /** Every type on the pasteboard, including the raw macOS markers in SKIPPED_FORMATS when present. */
  availableFormats(): Promise<string[]>;
  readText(): Promise<string>;
  writeText(text: string): Promise<void>;
}

/** Pasteboard types that say "do not remember this". */
export const SKIPPED_FORMATS = ['org.nspasteboard.ConcealedType', 'org.nspasteboard.TransientType', 'org.nspasteboard.AutoGeneratedType', 'com.agilebits.onepassword', 'com.typeit4me.clipping'];
export const MAX_TEXT_BYTES = 20 * 1024;
export const MAX_TOTAL_BYTES = 2 * 1024 * 1024;
export const MAX_PINNED = 20;
export const POLL_MS = 500;

const hashOf = (text: string) => createHash('sha1').update(text).digest('hex');
const firstLine = (text: string) => {
  const line = text.replace(/\s+/g, ' ').trim();
  return line.length > 140 ? line.slice(0, 139) + '…' : line;
};

export function toItem(text: string, now = Date.now()): ClipboardItem {
  const bytes = Buffer.byteLength(text, 'utf8');
  const trimmed = text.trim();
  let kind: ClipboardItem['kind'] = 'text';
  try { const u = new URL(trimmed); if ((u.protocol === 'http:' || u.protocol === 'https:') && !/\s/.test(trimmed)) kind = 'url'; } catch { /* not a URL */ }
  return { id: randomUUID(), kind, text, preview: firstLine(text), host: kind === 'url' ? new URL(trimmed).hostname : undefined, lines: text.split('\n').length, bytes, at: now, pinned: false };
}

export class ClipboardStore extends EventEmitter {
  private items: ClipboardItem[] = [];
  private timer: NodeJS.Timeout | null = null;
  private lastHash: string | null = null;
  private ignoreHash: string | null = null;
  private paused = false;
  private enabled = false;
  private limit = 50;
  private queue: Promise<unknown> = Promise.resolve();
  private loaded = false;
  private polling = false;
  constructor(private file: string, private pasteboard: Pasteboard, private pollMs = POLL_MS) { super(); }

  current(): ClipboardSnapshot {
    return { ...EMPTY_CLIPBOARD, enabled: this.enabled, paused: this.paused, items: this.items, limit: this.limit };
  }
  private emitState() { this.emit('change', this.current()); }
  private serial<T>(run: () => Promise<T>): Promise<T> {
    const next = this.queue.then(run, run);
    this.queue = next.catch(() => {});
    return next;
  }

  async load(): Promise<void> {
    try {
      const raw = JSON.parse(await fs.readFile(this.file, 'utf8'));
      if (Array.isArray(raw.items)) {
        this.items = raw.items.filter((v: unknown): v is ClipboardItem => {
          const i = v as ClipboardItem;
          return !!i && typeof i === 'object' && typeof i.id === 'string' && typeof i.text === 'string' && (i.kind === 'text' || i.kind === 'url');
        }).map((i: ClipboardItem) => ({ ...toItem(i.text, i.at), id: i.id, pinned: !!i.pinned })).slice(0, 200);
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') logEvent('notchlight', 'clipboard history could not be read; starting empty');
    }
    this.loaded = true;
    this.enforce();
    this.emitState();
  }

  private async persist(): Promise<void> {
    await fs.mkdir(path.dirname(this.file), { recursive: true });
    const temporary = `${this.file}.${randomUUID()}.tmp`;
    try {
      await fs.writeFile(temporary, JSON.stringify({ items: this.items }, null, 1) + '\n', { mode: 0o600 });
      await fs.rename(temporary, this.file);
    } finally { await fs.rm(temporary, { force: true }).catch(() => {}); }
  }

  /** Turn capture on or off; off stops the poller and forgets nothing. */
  configure(enabled: boolean, limit: number): void {
    const size = [20, 50, 100].includes(limit) ? limit : 50;
    const changed = enabled !== this.enabled || size !== this.limit;
    this.enabled = enabled; this.limit = size;
    if (enabled && !this.timer) {
      // What is there now was copied before we were asked to watch; the poller starts after that is noted.
      this.timer = setTimeout(() => {}, 0);
      void this.safeRead().then(read => { this.lastHash = read?.hash ?? null; if (this.enabled) this.timer = setInterval(() => void this.poll(), this.pollMs); });
      logEvent('notchlight', 'clipboard capture on');
    } else if (!enabled && this.timer) {
      clearInterval(this.timer); this.timer = null;
      logEvent('notchlight', 'clipboard capture off');
    }
    if (this.enforce() || changed) { void this.serial(() => this.persist()).catch(() => {}); this.emitState(); }
  }

  setPaused(paused: boolean): void {
    if (typeof paused !== 'boolean' || paused === this.paused) return;
    this.paused = paused;
    if (!paused) void this.safeRead().then(read => { this.lastHash = read?.hash ?? null; });
    logEvent('notchlight', `clipboard capture ${paused ? 'paused' : 'resumed'}`);
    this.emitState();
  }

  stop(): void { if (this.timer) clearInterval(this.timer); this.timer = null; }

  /** Read the pasteboard if it is safe to; null when concealed, transient, empty or too large. */
  private async safeRead(): Promise<{ text: string; hash: string } | null> {
    try {
      const formats = await this.pasteboard.availableFormats();
      if (formats.some(f => SKIPPED_FORMATS.includes(f))) return null;
      const text = await this.pasteboard.readText();
      if (!text || !text.trim()) return null;
      if (Buffer.byteLength(text, 'utf8') > MAX_TEXT_BYTES) return null;
      return { text, hash: hashOf(text) };
    } catch { return null; }
  }

  /** One tick of the watcher. Public so tests can drive it without waiting. */
  async poll(): Promise<void> {
    if (!this.enabled || this.paused || !this.loaded || this.polling) return;
    this.polling = true;
    try {
      const read = await this.safeRead();
      if (!read || !this.enabled || this.paused) return;
      if (read.hash === this.lastHash) return;
      this.lastHash = read.hash;
      if (read.hash === this.ignoreHash) { this.ignoreHash = null; return; }
      this.remember(read.text);
    } finally { this.polling = false; }
  }

  private remember(text: string): void {
    const existing = this.items.find(i => i.text === text);
    if (existing) {
      this.items = [{ ...existing, at: Date.now() }, ...this.items.filter(i => i !== existing)];
    } else {
      this.items = [toItem(text), ...this.items];
    }
    this.enforce();
    void this.serial(() => this.persist()).catch(() => {});
    this.emitState();
  }

  /** Apply the caps. Pinned items survive the history size but not the byte or pin budgets. Returns whether anything was dropped. */
  private enforce(): boolean {
    const before = this.items.length;
    let pins = 0;
    const kept: ClipboardItem[] = [];
    let unpinned = 0, bytes = 0;
    for (const item of this.items) {
      if (item.pinned) { if (pins >= MAX_PINNED) continue; pins++; }
      else { if (unpinned >= this.limit) continue; unpinned++; }
      if (bytes + item.bytes > MAX_TOTAL_BYTES) continue;
      bytes += item.bytes;
      kept.push(item);
    }
    this.items = kept;
    return kept.length !== before;
  }

  private find(id: unknown): ClipboardItem {
    const item = typeof id === 'string' && this.items.find(i => i.id === id);
    if (!item) throw new Error('That item is no longer in the history.');
    return item;
  }

  /** Put an item back on the pasteboard. The poller ignores this one write. */
  copy(id: unknown): Promise<void> {
    return this.serial(async () => {
      const item = this.find(id);
      this.ignoreHash = hashOf(item.text);
      await this.pasteboard.writeText(item.text);
      this.lastHash = this.ignoreHash;
      this.items = [{ ...item, at: Date.now() }, ...this.items.filter(i => i !== item)];
      await this.persist();
      this.emitState();
    });
  }

  pin(id: unknown, pinned: unknown): Promise<void> {
    if (typeof pinned !== 'boolean') return Promise.reject(new Error('Invalid pin.'));
    return this.serial(async () => {
      const item = this.find(id);
      if (pinned && !item.pinned && this.items.filter(i => i.pinned).length >= MAX_PINNED) throw new Error(`Up to ${MAX_PINNED} items can be pinned. Unpin one first.`);
      this.items = this.items.map(i => i === item ? { ...i, pinned } : i);
      this.enforce();
      await this.persist();
      this.emitState();
    });
  }

  remove(id: unknown): Promise<void> {
    return this.serial(async () => {
      const item = this.find(id);
      this.items = this.items.filter(i => i !== item);
      await this.persist();
      this.emitState();
    });
  }

  /** Forget the history. Pins stay unless asked for explicitly. */
  clear(includePinned: unknown): Promise<void> {
    if (typeof includePinned !== 'boolean') return Promise.reject(new Error('Invalid clear.'));
    return this.serial(async () => {
      this.items = includePinned ? [] : this.items.filter(i => i.pinned);
      await this.persist();
      logEvent('notchlight', `clipboard history cleared${includePinned ? ' including pins' : ''}`);
      this.emitState();
    });
  }
}
