import fs from 'node:fs/promises';
import {build} from 'esbuild';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const dir = path.dirname(fileURLToPath(import.meta.url));
const dynamic=process.argv.includes('--dynamic'),short=dynamic||process.argv.includes('--short');
const track=dynamic?JSON.parse(await fs.readFile(path.join(dir,'dynamic-track.json'),'utf8')):null;
if(track)track.levels=JSON.parse(await fs.readFile(path.join(dir,'assets/ganja-levels.json'),'utf8'));
const parts = await Promise.all(['nl-theme.jsx','nl-faces.jsx','nl-desktop.jsx',short?'film-short.jsx':'film.jsx'].map(f=>fs.readFile(path.join(dir,'src',f),'utf8')));
await fs.mkdir(path.join(dir,'dist'),{recursive:true});
await build({stdin:{contents:`import React from 'react'; import {createRoot} from 'react-dom/client'; import {flushSync} from 'react-dom';\nconst AD_TRACK=${JSON.stringify(track)};\nfunction soundtrackTime(t){return AD_TRACK?t-Math.max(0,Math.min(t-AD_TRACK.pause,AD_TRACK.play-AD_TRACK.pause)):t;}\n${parts.join('\n')}`,resolveDir:dir,loader:'jsx'},bundle:true,minify:true,define:{'process.env.NODE_ENV':'"production"'},outfile:path.join(dir,dynamic?'dist/film-dynamic.js':short?'dist/film-short.js':'dist/film.js')});
console.log('Built Notchlight film.');
